print("Welcome to the Band Name Generator .")
city = input("which city did you grow up in?\n")
print(city)
pet = input("what is name of a pet ?\n")
print("your band name could be:" + city + " " + pet)
